### ISSUE TITLE
Listing Keys from a Bucket no longer works

### ISSUE THREAD

**Issue by ghost** [marianoguerra/tanodb#11]
Due to a change in what riak_core expects, the instructions for the chapter 'Listing Keys from a Bucket' no longer works because of the following causing a badmatch:
https://github.com/marianoguerra/tanodb/blob/3fba49431c68f14f35d088b5e98839d81ea468ab/apps/tanodb/src/tanodb_coverage_fsm.erl#L27-L29

Changing it to this fixes it:
```erlang
{Request, allup, 1, 1, tanodb, tanodb_vnode_master, Timeout, riak_core_coverage_plan, State}.
```

**Comment by marianoguerra** [comment]
hi, 

thanks for reporting!

yes, it doesn't work any more, the new riak core tutorial has a version that works: http://marianoguerra.org/tmp/riak-core-tutorial/coverage-calls.html

Once I finished publishing the individual chapters I will add a note on the little riak core book about this updated resource.

The new code is here: https://gitlab.com/marianoguerra/tanodb

**Comment by ghost** [comment]
Awesome, thanks a lot.

I'll close this now then :-)
