### ISSUE TITLE
couldn't find 'nodename' in ../tanodb_config/tanodb.conf

### ISSUE THREAD

**Issue by zhjunqin** [marianoguerra/tanodb#6]
I met following problem when I try to do rebar3 run

:~/tanodb/tanodb (ping-as-a-service-fix-1)$ rebar3 run
===> Verifying dependencies...
===> Compiling tanodb
===> Running cuttlefish schema generator
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/id/tanodb/tanodb/_build/default/lib
          /home/id/tanodb/tanodb/apps
          /usr/local/lib/erlang/lib
          /home/id/tanodb/tanodb/_build/default/rel
===> Resolved tanodb-0.1.0
===> Dev mode enabled, release will be symlinked
===> release successfully created!
vm.args needs to have a -name parameter.
  -sname is not supported.
  couldn't find 'nodename' in ../tanodb_config/tanodb.conf
  $PWD is /home/id/tanodb/tanodb

I have tried follow "Little Riak Core Book" to install through template, but I still got above problem.
Then I use commit "ping-as-a-service-fix-1", problem is same 
I also checked file, it is there.
~/tanodb/tanodb/config (ping-as-a-service-fix-1)$ ll vm.args

My rebar3 version is
~$rebar3 -v
rebar 3.2.0 on Erlang/OTP 18 Erts 7.0

Anyone met this before?
Thanks a lot!

**Comment by hampusbergstrom** [comment]
Got the exact same problem. Can't seem to figure it out. 

Using:
Rebar 3.1.1
Erlang 18.3
Riak 2.1.4

**Comment by zhjunqin** [comment]
it works after I removed one line with "tanodb_config" in bin/tanodb
