### ISSUE TITLE
when you run rebar3 run (using R18)

### ISSUE THREAD

**Issue by gyanaggarwal** [marianoguerra/tanodb#7]
vm.args needs to have a -name parameter.
  -sname is not supported.
  couldn't find 'nodename' in ../tanodb_config/tanodb.conf
  $PWD is /Users/gyanendraaggarwal/tanodb

**Comment by liuzhen** [comment]
kind broken, must explicitly set `platform_etc_dir' somehow.

**Comment by marianoguerra** [comment]
@gyanaggarwal for now try running

```
make console
```

when the PR above is merged then "rebar3 run" will work again.

**Comment by gyanaggarwal** [comment]
when I do make console I get the same error

**Comment by marianoguerra** [comment]
this should work now:

    make release
    make console # or rebar3 run
